use hospital;

DELIMITER |
CREATE PROCEDURE getAllDocteur()
    NOT DETERMINISTIC
    READS SQL DATA
    LANGUAGE SQL
    CONTAINS SQL
BEGIN
    START TRANSACTION;
        SELECT * FROM docteur;
    COMMIT;
END |

DELIMITER ;
